### PR TITLE
Dolphins

### PR DESCRIPTION
**Pull request by batterystaples**
@EpicGames/developers @EpicGames/artv2-admin @EpicTeamAdmin

### CODE REVIEW

**Comment by robclancy** [comment]
https://www.youtube.com/watch?v=dwLCjZVEtpE

**Comment by gak** [comment]
:facepalm:

**Comment by johnson-christopher** [comment]
@nerual The children are acting up again.

**Comment by Fortyseven** [comment]
People fucking suck.

**Comment by capnslipp** [comment]
Okay, how do I unsubscribe from e-mail notifications for this?  Unsubscribe button in the e-mail has no effect.  Turning off all notifications for this issue has no effect.  I guess I just need to leave the EpicGames/developers group?

**Comment by jleppert** [comment]
Yes they are. For shame!

**Review by waltercool — COMMENTED** [review]
Can confirm

**Comment by komocode** [comment]
report and move on.

**Comment by urmumlolxd699** [comment]
"Samy is my hero"

**Comment by CQD** [comment]
For those who got annoyed: Go to https://github.com/notifications and unsubscribe.

**Comment by mjevange** [comment]
> Okay, how do I unsubscribe from e-mail notifications for this? Unsubscribe button in the e-mail has no effect. Turning off all notifications for this issue has no effect. I guess I just need to leave the EpicGames/developers group?

Yeah pretty much just leave

**Pull request closed without merging**
