### PR TITLE
owo

### PR DESCRIPTION
**Pull request by resynth1943**
# uwu

I think this shouwd be mewged, because it wiww impwuv the usefuwnyess of the WEADME incwedibwy. Pwease considew adding this patch to this wepositowy. It wiww intwoduce a wowwdwide change to suppowt, and the functionyawity of Mawkdown. 

(✿ ͡❛ ͜ʖ ͡❛)

### CODE REVIEW

**Comment by resynth1943** [comment]
@TheEvilSkeleton 😳 can you approve

**Review by resynth1943 — COMMENTED** [review]
thanks u for submitting Kazuki-chan 😳 😳 😳 🏖️

**Review by Messhias — APPROVED** [review]
hmmmmm

**Review by jbmagination — APPROVED** [review]
best pull request, please merge

**Comment by jadeastar** [comment]
+1 please merge

**Review by jgowdy — CHANGES_REQUESTED** [review]
Stop.

**Comment by tsejerome** [comment]
(✿ ͡👁️ ͜ʖ ͡👁️)

**Comment by vidyagirl** [comment]
this is the pull request ever

**Pull request closed without merging**
