### PR TITLE
Create repo-lockdown GitHub action

### PR DESCRIPTION
**Pull request by bcbee**
This change adds a new GitHub action which automatically closes all GitHub issues or pull requests and redirects users to Unreal Engine support.

### CODE REVIEW

**Review by ryan-hummer — APPROVED** [review]

**Comment by Beheadedstraw** [comment]
Thanks for the quick fix guys.

**Comment by iuriguilherme** [comment]
LGTM

PS: About time, TYVM

**Comment by ksweeley** [comment]
Thank you for immediately pushing this fix. Hopefully this stops any future attempt to cause notification email spam through a pull request. Didn't even know that notification email spam through a Github pull request was even possible before these recent pull requests.

**Comment by TheModdersDen** [comment]
Thank heavens, an end to the notification nag...

**Comment by polkovnikov-ph** [comment]
I suspect this won't be enough, because comments are not closed yet, and the tag still exists.

**Comment by Sewer56** [comment]
Question:

If someone opens a pull requests and tags the developers group with 400k members, wouldn't these people be notified of the pull request being closed by the bot? 

Or would it only do it to the person that created the PR? This is a question worth answering.

**Comment by i5o** [comment]
Thanks for doing it. Sad that the old PR got removed instead of saved as a "happy little error".

**Comment by iuriguilherme** [comment]
Yes, the fact that there's such a group is the root problem. The organization mantainers would either have to come up with an alternative to achieve the same functionality or asking nicely to Github to get a special treatment for this case. Github is made on assumptions that doesn't foresee such an use case so this "worked" until yesterday when the problem became obvious.

**Comment by bcbee** [comment]
> If someone opens a pull requests and tags the developers group with 400k members, wouldn't these people be notified of the pull request being closed by the bot?

Yes, this is a stop-gap solution that limits the number of replies to any given thread by closing and locking within ~30s. We are working with GitHub to identify and implement a long term solution to prevent this kind of spam.

I'm going to lock this thread to prevent any replies from referencing the developers group. Thanks you for your feedback!

**Pull request merged**
